name: credit-system-backend
services:
- name: web
  source_dir: /
  github:
    repo: yhwh80/credit-system-backend
    branch: master
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  http_port: 8080
  routes:
  - path: /
