name: credit-system-backend
services:
- name: web
  source_dir: /
  github:
    repo: yhwh80/credit-system-backend
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGO_URI
    value: mongodb+srv://sgpyhwh1980:TgspjefY2DZAO7l5@credit-system-prod.ahbdosi.mongodb.net/?retryWrites=true&w=majority&appName=credit-system-prod
    type: SECRET
  - key: SESSION_SECRET
    value: 8ec046098e7b84e00f5eb1cbd0afd62697f0dc385f3ba2e4a91a4c4d0de406db
    type: SECRET
  - key: PORT
    value: "8080"
  http_port: 8080
  routes:
  - path: /
